ahu_path_1:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH21_Cooling_Coil
    ahu: urn:sdh#RAH21
    equipment: urn:sdh#RAH21_Supply_Fan
  user_selected: true
ahu_path_2:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH19_Cooling_Coil
    ahu: urn:sdh#RAH19
    equipment: urn:sdh#RAH19_Supply_Fan
  user_selected: false
ahu_path_3:
  path:
    plant: urn:sdh#CHM-3
    water_loop: urn:sdh#MDF_Chilled_Water_Loop
    coil: urn:sdh#AH4_Cooling_Coil
    ahu: urn:sdh#AH4
    equipment: urn:sdh#AH4_Supply_Fan
  user_selected: false
ahu_path_4:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#SCHW_and_AH1_Water_Loop
    coil: urn:sdh#AH1A_Cooling_Coil
    ahu: urn:sdh#AH1A
    equipment: urn:sdh#AH1A_Supply_Fan
  user_selected: false
ahu_path_5:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Office_Space_Water_Loop
    coil: urn:sdh#AH2A_Cooling_Coil
    ahu: urn:sdh#AH2A
    equipment: urn:sdh#AH2A_Supply_Fan
  user_selected: false
ahu_path_6:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH18_Cooling_Coil
    ahu: urn:sdh#RAH18
    equipment: urn:sdh#RAH18_Supply_Fan
  user_selected: false
ahu_path_7:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH07_Cooling_Coil
    ahu: urn:sdh#RAH07
    equipment: urn:sdh#RAH07_Supply_Fan
  user_selected: false
ahu_path_8:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH13_Cooling_Coil
    ahu: urn:sdh#RAH13
    equipment: urn:sdh#RAH13_Supply_Fan
  user_selected: false
ahu_path_9:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH05_Cooling_Coil
    ahu: urn:sdh#RAH05
    equipment: urn:sdh#RAH05_Supply_Fan
  user_selected: false
ahu_path_10:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH01_Cooling_Coil
    ahu: urn:sdh#RAH01
    equipment: urn:sdh#RAH01_Supply_Fan
  user_selected: false
ahu_path_11:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH11_Cooling_Coil
    ahu: urn:sdh#RAH11
    equipment: urn:sdh#RAH11_Supply_Fan
  user_selected: false
ahu_path_12:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH14_Cooling_Coil
    ahu: urn:sdh#RAH14
    equipment: urn:sdh#RAH14_Supply_Fan
  user_selected: false
ahu_path_13:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH06_Cooling_Coil
    ahu: urn:sdh#RAH06
    equipment: urn:sdh#RAH06_Supply_Fan
  user_selected: false
ahu_path_14:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH23_Cooling_Coil
    ahu: urn:sdh#RAH23
    equipment: urn:sdh#RAH23_Supply_Fan
  user_selected: false
ahu_path_15:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH04_Cooling_Coil
    ahu: urn:sdh#RAH04
    equipment: urn:sdh#RAH04_Supply_Fan
  user_selected: false
ahu_path_16:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Office_Space_Water_Loop
    coil: urn:sdh#AH2B_Cooling_Coil
    ahu: urn:sdh#AH2B
    equipment: urn:sdh#AH2B_Return_Fan
  user_selected: false
ahu_path_17:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH20_Cooling_Coil
    ahu: urn:sdh#RAH20
    equipment: urn:sdh#RAH20_Supply_Fan
  user_selected: false
ahu_path_18:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#SCHW_and_AH1_Water_Loop
    coil: urn:sdh#AH1B_Cooling_Coil
    ahu: urn:sdh#AH1B
    equipment: urn:sdh#AH1B_Supply_Fan
  user_selected: false
ahu_path_19:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH09_Cooling_Coil
    ahu: urn:sdh#RAH09
    equipment: urn:sdh#RAH09_Supply_Fan
  user_selected: false
ahu_path_20:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH12_Cooling_Coil
    ahu: urn:sdh#RAH12
    equipment: urn:sdh#RAH12_Supply_Fan
  user_selected: false
ahu_path_21:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH25_Cooling_Coil
    ahu: urn:sdh#RAH25
    equipment: urn:sdh#RAH25_Supply_Fan
  user_selected: false
ahu_path_22:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Office_Space_Water_Loop
    coil: urn:sdh#AH2B_Cooling_Coil
    ahu: urn:sdh#AH2B
    equipment: urn:sdh#AH2B_Supply_Fan
  user_selected: false
ahu_path_23:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH10_Cooling_Coil
    ahu: urn:sdh#RAH10
    equipment: urn:sdh#RAH10_Supply_Fan
  user_selected: false
ahu_path_24:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH02_Cooling_Coil
    ahu: urn:sdh#RAH02
    equipment: urn:sdh#RAH02_Supply_Fan
  user_selected: false
ahu_path_25:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Office_Space_Water_Loop
    coil: urn:sdh#AH2A_Cooling_Coil
    ahu: urn:sdh#AH2A
    equipment: urn:sdh#AH2A_Return_Fan
  user_selected: false
ahu_path_26:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH22_Cooling_Coil
    ahu: urn:sdh#RAH22
    equipment: urn:sdh#RAH22_Supply_Fan
  user_selected: false
ahu_path_27:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH26_Cooling_Coil
    ahu: urn:sdh#RAH26
    equipment: urn:sdh#RAH26_Supply_Fan
  user_selected: false
ahu_path_28:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH08_Cooling_Coil
    ahu: urn:sdh#RAH08
    equipment: urn:sdh#RAH08_Supply_Fan
  user_selected: false
ahu_path_29:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH03_Cooling_Coil
    ahu: urn:sdh#RAH03
    equipment: urn:sdh#RAH03_Supply_Fan
  user_selected: false
ahu_path_30:
  path:
    plant: urn:sdh#CH2
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH24_Cooling_Coil
    ahu: urn:sdh#RAH24
    equipment: urn:sdh#RAH24_Supply_Fan
  user_selected: false
ahu_path_31:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH17_Cooling_Coil
    ahu: urn:sdh#RAH17
    equipment: urn:sdh#RAH17_Supply_Fan
  user_selected: false
ahu_path_32:
  path:
    plant: urn:sdh#CH1
    water_loop: urn:sdh#Secondary_Chilled_Water_Loop
    coil: urn:sdh#RAH15_Cooling_Coil
    ahu: urn:sdh#RAH15
    equipment: urn:sdh#RAH15_Supply_Fan
  user_selected: false
