end_user_1:
  attributes:
    equipment: http://berkeley.edu/climatechamber#damper_SC_VAV
    equipment_type: https://brickschema.org/schema/Brick#Damper
    obj_name: vav_dmpr_pos_6
    t_type: https://brickschema.org/schema/Brick#Damper_Position_Sensor
  selected: true
